name: Checking-with-Linter
on:
  push:
    branches:
      - adding_jest_job
jobs:
  jest-execution:
    name: jest-execution
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run jest tests
        run: npm test

  linter-execution:
    name: linter-execution
    runs-on: ubuntu-latest
    needs: jest-execution
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Linter execution
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: nodejs_example
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true
