name: My workflow

on:
  push:
    branches:
      - react_app_deploy

jobs:
  build:
    name: Build project job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Change App.js
        uses: ./.github/actions/change_loader_image_action
        with:
          gifs_alternative: '[
            "https://pixelpapa.com/wp-content/uploads/2018/11/2.gif",
            "https://pixelpapa.com/wp-content/uploads/2018/11/3.gif",
            "https://pixelpapa.com/wp-content/uploads/2018/11/9.gif",
            "https://miro.medium.com/max/489/0*cWpsf9D3g346Va20.gif",
            ]'
      - run: |
          git config user.name jovisal1
          git config user.email pvidalsalvador@gmail.com
          git add .
          git commit -m "App.js modification with random gif"
          git push origin react_app_deploy
      - name: Building app
        run: |
          npm install
          npm run build
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: static-generated-files
          path: build

  deploy:
    name: Deploy project job
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts from build job
        uses: actions/download-artifact@v2
        with:
          name: static-generated-files
      - name: Deploy to foo-bar.surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: "draconian-cap.surge.sh"
          project: "."
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
